In [1]:
#run this cell
import warnings

warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import os


import gymnasium as gym


import collections
import argparse

import math
import random
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count

import seaborn as sns
import pandas as pd
from collections import defaultdict

In [2]:
import torch
import torch.utils.data as utils
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F

import torch.optim as optim


from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [4]:
from MainCode.env import CustomTensorDataReader, Simulator, Window, Budget

In [5]:
bg = Budget()

In [37]:
bg.get_budget()
bg.action

306

In [74]:
bg.action

228

In [11]:
bg.window.shape[0]

188

In [38]:
bg.expenses

188

In [11]:
(bg.action - bg.expenses) / bg.expenses * 100

12.23404255319149

In [40]:
bg.ratio 

1.63

In [11]:
bg.pr * 100

832.0

In [41]:
bg.pr * -1

-0.63

In [10]:
bg.ratio * 100

540.9574468085107

In [6]:
bg.budget

1

In [6]:
bg.set_expenses()

In [7]:
bg.expenses

188

In [13]:
bg.window.shape[1]

1553

In [8]:
import gymnasium as gym

In [71]:
action_space = gym.spaces.Box(low=1, high=1553 * 2, dtype=int)

In [72]:
action_space.sample()[0]

2079

In [5]:
td = CustomTensorDataReader()

In [12]:
td = Simulator()

In [5]:
wd = Window()

In [6]:
sd = Simulator()

In [7]:
sd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)

In [18]:
sd.target_window.shape[0]

188

In [10]:
new = (1 - sd.target_data)

In [11]:
new

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [23]:
ex = Expenses()

In [24]:
ex.set_expenses(sd.target_window.shape[0])

In [25]:
ex.expenses

188

In [31]:
sd.window.shape[0]

188

In [33]:
sd.target_window.sum()

0.0

In [8]:
sd.window

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [8]:
sd.target_data[sd.current_step]

0.0

In [9]:
sd.target_data[sd.window]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:
sd.window

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [13]:
td.data

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [14]:
td.data.shape

torch.Size([62223, 1553, 17])

In [8]:
td.target_data.shape

(14863575,)

In [9]:
td.index

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [15]:
td.current_step

0

In [18]:
window = [td.index[td.current_step][0] : td.index[td.current_step][1]]

SyntaxError: invalid syntax (1227755194.py, line 1)

In [17]:
td.data[td.index[td.current_step][0] : td.index[td.current_step][1]]

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [16]:
td.data

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 