In [1]:
#run this cell
import warnings

warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import os


import gymnasium as gym


import collections
import argparse

import math
import random
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count

import seaborn as sns
import pandas as pd
from collections import defaultdict

In [2]:
import torch
import torch.utils.data as utils
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F

import torch.optim as optim


from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [4]:
# env = gym.make("CartPole-v1")

In [4]:
# env.reset()

In [4]:
from MainCode.env import Simulator, Window, Budget, CustomTensorDataReader

In [8]:
dr = CustomTensorDataReader()

In [9]:
dr.data

array([[[1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [10]:
dr.target_data

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
for i in range(1, 62220):
    

In [7]:
dr.index.shape

(62224, 2)

In [5]:
bg = Budget()

In [5]:
wd = Window()

In [6]:
wd.current_index

56036

In [26]:
wd.current_index = 0

In [27]:
wd.current_index

0

In [28]:
locations = deque()
while wd.current_index <= 62220:
    target = wd.target_window.sum()
    if target >= 1:
        locations.append(wd.current_index)
    wd.current_index += 1
    wd.update_window()


In [ ]:
        # self.targets_locations = np.array([
        #     9899, 10000, 10394, 10419, 10468, 10548, 10614, 10758, 10798,
        #     10883, 11384, 11396, 11471, 11542, 11830, 12030, 12113, 12209,
        #     12299, 12517, 12549, 13211, 13467, 13802, 13831, 13932, 14841,
        #     14935, 15300, 15512, 15903, 20993, 21005, 21038, 21046, 21082,
        #     21305, 21347, 21422, 21466, 21480, 21486, 21510, 21519, 21712,
        #     22172, 22319, 22793, 23122, 23327, 23503, 23625, 23809, 24117,
        #     24145, 24515, 25323, 25331, 25421, 25601, 25955, 26382, 27441,
        #     27545, 27634, 27643, 27814, 27822, 27913, 27920, 28144, 28626,
        #     28666, 29313, 30206, 30372, 30450, 30489, 30562, 30764, 30798,
        #     31006, 31049, 31271, 31412, 31556, 31574, 31640, 31658, 31670,
        #     31799, 31868, 31889, 32064, 32350, 32452, 32538, 32618, 32683,
        #     32808, 32839, 33217, 33271, 33411, 33465, 34227, 34234, 34715,
        #     34718, 34830, 35784, 36329, 37017, 37303, 37747, 38507, 39012,
        #     39332, 39611, 40315, 40560, 41646, 41867, 42036, 42166, 42841,
        #     43807, 44486, 44543, 44559, 44579, 44586, 44607, 44799, 44884,
        #     45105, 45218, 45439, 45450, 45545, 45584, 45935, 46420, 46568,
        #     46947, 46979, 47245, 47256, 48194, 48517, 48531, 48544, 48551,
        #     48591, 48660, 48692, 48695, 48721, 48816, 48933, 48972, 48981,
        #     49006, 49084, 49163, 49311, 49340, 49354, 49427, 49586, 49642,
        #     49689, 49899, 50187, 50199, 50216, 50228, 50345, 50371, 50543,
        #     50561, 50575, 50594, 50945, 50999, 51199, 51257, 51290, 51412,
        #     51591, 51598, 51606, 51616, 51636, 51644, 51649, 51657, 51699,
        #     51700, 51711, 51731, 51856, 52224, 54549, 55751
        # ])

        # self.current_index = []
        # for i in range(0, 62220):
        #     if i in self.targets_locations:
        #         continue
        #     else:
        #         self.current_index.append(i)

In [21]:
wd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [30]:
wd.current_index = locations[0]

In [32]:
wd.update_window()

In [33]:
wd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [29]:
locations

deque([9899,
       10000,
       10394,
       10419,
       10468,
       10548,
       10614,
       10758,
       10798,
       10883,
       11384,
       11396,
       11471,
       11542,
       11830,
       12030,
       12113,
       12209,
       12299,
       12517,
       12549,
       13211,
       13467,
       13802,
       13831,
       13932,
       14841,
       14935,
       15300,
       15512,
       15903,
       20993,
       21005,
       21038,
       21046,
       21082,
       21305,
       21347,
       21422,
       21466,
       21480,
       21486,
       21510,
       21519,
       21712,
       22172,
       22319,
       22793,
       23122,
       23327,
       23503,
       23625,
       23809,
       24117,
       24145,
       24515,
       25323,
       25331,
       25421,
       25601,
       25955,
       26382,
       27441,
       27545,
       27634,
       27643,
       27814,
       27822,
       27913,
       27920,
       28144,
       

In [35]:
target_locations = np.array(locations)

In [42]:
current_index = []
for i in range(0, 62220):
    if i in target_locations:
        continue
    else:
        current_index.append(i)

In [45]:
current_index = np.array(current_index)

In [46]:
current_index_tensor = torch.tensor(current_index)

In [47]:
current_index_tensor

tensor([    0,     1,     2,  ..., 62217, 62218, 62219])

In [48]:
torch.save(current_index_tensor, 'current_index.pt')

In [43]:
current_index

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [44]:
np.save(current_index, 'current_index.npy')

TypeError: expected str, bytes or os.PathLike object, not list

In [34]:
np.array(locations)

array([ 9899, 10000, 10394, 10419, 10468, 10548, 10614, 10758, 10798,
       10883, 11384, 11396, 11471, 11542, 11830, 12030, 12113, 12209,
       12299, 12517, 12549, 13211, 13467, 13802, 13831, 13932, 14841,
       14935, 15300, 15512, 15903, 20993, 21005, 21038, 21046, 21082,
       21305, 21347, 21422, 21466, 21480, 21486, 21510, 21519, 21712,
       22172, 22319, 22793, 23122, 23327, 23503, 23625, 23809, 24117,
       24145, 24515, 25323, 25331, 25421, 25601, 25955, 26382, 27441,
       27545, 27634, 27643, 27814, 27822, 27913, 27920, 28144, 28626,
       28666, 29313, 30206, 30372, 30450, 30489, 30562, 30764, 30798,
       31006, 31049, 31271, 31412, 31556, 31574, 31640, 31658, 31670,
       31799, 31868, 31889, 32064, 32350, 32452, 32538, 32618, 32683,
       32808, 32839, 33217, 33271, 33411, 33465, 34227, 34234, 34715,
       34718, 34830, 35784, 36329, 37017, 37303, 37747, 38507, 39012,
       39332, 39611, 40315, 40560, 41646, 41867, 42036, 42166, 42841,
       43807, 44486,

In [6]:
obs, info = wd.reset()

In [9]:
wd.index

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [8]:
obs.shape

(1553, 17)

In [10]:
obs[0]

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 9.0000e+00, 1.0000e+00,
       2.0000e+00, 3.0000e+00, 9.0000e+00, 1.2371e+04, 9.0000e+00,
       1.2000e+01, 6.0000e+00, 1.3000e+01, 8.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00], dtype=float32)

In [11]:
wd.reset()

(array([[1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        [1., 2., 3., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 {})

In [8]:
wd.current_index

25539

In [7]:
wd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.], dtype=float32)

In [12]:
wd.current_index

19406

In [13]:
wd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)

In [13]:
wd.current_step

0

In [14]:
obs.shape

(1553, 17)

In [13]:
obs.shape

(188, 1553, 17)

In [14]:
wd.current_index

41189

In [7]:
wd.current_index


39460

In [20]:
wd.index[wd.current_index][0]

11094180

In [17]:
wd.data[
    wd.index
]

IndexError: index 62413 is out of bounds for axis 0 with size 62223

In [22]:
wd.current_index

41189

In [24]:
wd.current_index

41189

In [27]:
wd.index[wd.current_index][0]

11094180

In [28]:
wd.index[wd.current_index][1]

11094405

In [31]:
wd.data.shape

(62223, 1553, 17)

In [33]:
wd.data[0].shape

(1553, 17)

In [29]:
wd.data[
    11094180:11094405
]

array([], shape=(0, 1553, 17), dtype=float32)

In [21]:
wd.index[
    
]

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [15]:
wd.data[
    wd.index[
        
    ]
]

array([], shape=(0, 1553, 17), dtype=float32)

In [9]:
wd.current_index

39460

In [44]:
wd.data[0].shape

(1553, 17)

In [47]:
wd.data[0]

array([[1., 2., 3., ..., 0., 0., 0.],
       [1., 2., 3., ..., 0., 0., 0.],
       [1., 2., 3., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [52]:
wd.data[wd.current_index][2]

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 1.0000e+01, 1.0000e+00,
       2.0000e+00, 3.0000e+00, 1.0000e+01, 1.1398e+04, 1.0000e+01,
       1.2000e+01, 6.0000e+00, 1.3000e+01, 8.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00], dtype=float32)

In [45]:
wd.data.shape

(62223, 1553, 17)

In [12]:
wd.index[wd.current_index]

array([927068, 927283])

In [40]:
wd.target_data.shape

(14863575,)

In [41]:
wd.index

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [38]:
wd.index.shape

(62224, 2)

In [36]:
wd.data.shape

(62223, 1553, 17)

In [35]:
wd.index[39460]

array([10726835, 10727030])

In [11]:
wd.data.shape

(1553, 17)

In [10]:
wd.index

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [7]:
wd.reset()

(array([], shape=(0, 1553, 17), dtype=float32), {})

In [8]:
wd.window

array([], shape=(0, 1553, 17), dtype=float32)

In [6]:
bg.data.shape

(62223, 1553, 17)

In [7]:
bg.starting_index_value

46343

In [8]:
bg.current_step

0

In [7]:
bg.window

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [7]:
bg.get_budget()

TypeError: Budget.get_budget() missing 1 required positional argument: 'input_action'

In [37]:
bg.get_budget()
bg.action

306

In [74]:
bg.action

228

In [11]:
bg.window.shape[0]

188

In [38]:
bg.expenses

188

In [11]:
(bg.action - bg.expenses) / bg.expenses * 100

12.23404255319149

In [40]:
bg.ratio 

1.63

In [11]:
bg.pr * 100

832.0

In [41]:
bg.pr * -1

-0.63

In [10]:
bg.ratio * 100

540.9574468085107

In [6]:
bg.budget

1

In [6]:
bg.set_expenses()

In [7]:
bg.expenses

188

In [13]:
bg.window.shape[1]

1553

In [8]:
import gymnasium as gym

In [71]:
action_space = gym.spaces.Box(low=1, high=1553 * 2, dtype=int)

In [72]:
action_space.sample()[0]

2079

In [5]:
td = CustomTensorDataReader()

In [12]:
td = Simulator()

In [5]:
wd = Window()

In [6]:
sd = Simulator()

In [7]:
sd.target_window

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)

In [18]:
sd.target_window.shape[0]

188

In [10]:
new = (1 - sd.target_data)

In [11]:
new

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [23]:
ex = Expenses()

In [24]:
ex.set_expenses(sd.target_window.shape[0])

In [25]:
ex.expenses

188

In [31]:
sd.window.shape[0]

188

In [33]:
sd.target_window.sum()

0.0

In [8]:
sd.window

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [8]:
sd.target_data[sd.current_step]

0.0

In [9]:
sd.target_data[sd.window]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:
sd.window

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [13]:
td.data

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [14]:
td.data.shape

torch.Size([62223, 1553, 17])

In [8]:
td.target_data.shape

(14863575,)

In [9]:
td.index

array([[       0,      188],
       [     188,      364],
       [     364,      576],
       ...,
       [14862950, 14863141],
       [14863141, 14863318],
       [14863318, 14863434]])

In [15]:
td.current_step

0

In [18]:
window = [td.index[td.current_step][0] : td.index[td.current_step][1]]

SyntaxError: invalid syntax (1227755194.py, line 1)

In [17]:
td.data[td.index[td.current_step][0] : td.index[td.current_step][1]]

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [16]:
td.data

tensor([[[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         [1., 2., 3.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 